config :designer, :required => [:runtime, :foundation, :desktop]
config :scroll_view, :required => [:runtime, :foundation, :desktop]
config :menu, :required => [:'experimental/scroll_view']

config :greenhouse,
  :required => [:sproutcore, :designer, :statechart],
  :theme => :ace,
  :css_theme => 'ace.greenhouse'
